Added testing
dkorn/manageiq-ansible-module pull request #16
Opened 2016-09-08 16:09 UTC by jaryn

I've addressed the review comments.

2016-09-19 12:41 UTC, dkorn commented on tests/test_container_provider.py
> +provider_hostname = "some-provider-hostname.tld"
shouldn't these constants be all capital letters?

2016-09-19 12:42 UTC, dkorn commented on tests/test_container_provider.py
> +hawkular_port = "54321"
perhaps this can also be a "real" port example, like "443"?

2016-09-19 12:59 UTC, dkorn commented on tests/test_container_provider.py
> +    # TODO(jaryn) This would ideally be inside test cases that need it.
IINM, this is possible after https://github.com/dkorn/manageiq-ansible-module/pull/15 is merged right?

2016-09-19 13:01 UTC, dkorn commented on tests/test_container_provider.py
> +    miq_api_class.return_value.post.return_value = dict(results=[
can we create another post return value for a delete action? (returns different fields)

2016-09-19 13:01 UTC, dkorn requested changes
needs a rebase and few inline comments/questions.

2016-09-22 04:35 UTC, jaryn commented on tests/test_container_provider.py
> +    miq_api_class.return_value.post.return_value = dict(results=[
The MIQ is using HTTP POST to do delete? Hmm Why doesn't it use DELETE instead?

2016-09-22 04:37 UTC, jaryn commented on tests/test_container_provider.py
> +    # TODO(jaryn) This would ideally be inside test cases that need it.
removed

2016-09-22 04:37 UTC, jaryn commented on tests/test_container_provider.py
> +hawkular_port = "54321"
done

2016-09-22 04:37 UTC, jaryn commented on tests/test_container_provider.py
> +provider_hostname = "some-provider-hostname.tld"
they are now

2016-09-22 14:45 UTC, dkorn commented on tests/test_container_provider.py
> +    miq_api_class.return_value.post.return_value = dict(results=[
they also support DELETE but IINM when using DELETE you don't get a response

2016-09-22 14:52 UTC, dkorn commented on tests/test_container_provider.py
> +provider_hostname = "some-provider-hostname.tld"
:+1:

2016-09-22 14:52 UTC, dkorn commented on tests/test_container_provider.py
> +hawkular_port = "54321"
:+1:

2016-09-23 08:29 UTC, jaryn commented on tests/test_container_provider.py
> +    miq_api_class.return_value.post.return_value = dict(results=[
Interesting.

I think we gonna need another mock for the different post.

 Anyway please merge as I think it is not a topic of this PR

2016-09-25 07:52 UTC, dkorn approved these changes

2016-09-25 07:52 UTC, merged