Add hawkular datawarehouse provider and example playbook
dkorn/manageiq-ansible-module pull request #53
Opened 2017-02-09 16:14 UTC by zgalor

Added hawkular datawarehouse provider to provider ansible module.
Also added a playbook example.

@dkorn PTAL

2017-02-11 10:04 UTC, dkorn commented
Please add the relevant details to the docs:

- manageiq_provider section in the README: https://github.com/dkorn/manageiq-ansible-module/blob/master/README.md#manageiq_provider-module

- provider types: https://github.com/dkorn/manageiq-ansible-module/pull/53/files#diff-1c9d8e7f51b7d3ee06e9a412ac9d0c79R48

- add an example: https://github.com/dkorn/manageiq-ansible-module/pull/53/files#diff-1c9d8e7f51b7d3ee06e9a412ac9d0c79R96

2017-02-11 10:04 UTC, dkorn requested changes

2017-02-11 10:04 UTC, dkorn commented on library/manageiq_provider.py
> +            endpoints = [manageiq.generate_openshift_endpoint('default', 'default', hostname, port, token)]
we should probably rename `generate_openshift_endpoint` to `generate_auth_key_endpoint` and `generate_amazon_endpoint` to `generate_user_password_endpoint`.
@cben what do you think?

2017-02-11 20:16 UTC, cben reviewed
Nice.  Smaller changes than I expected.

Should this use `hawkular_hostname`, `hawkular_port` params instead of `hostname`, `port`?  Probably not.

2017-02-11 20:16 UTC, cben commented on library/manageiq_provider.py
> +        'hawkular-datawarehouse': "ManageIQ::Providers::Hawkular::DatawarehouseManager"}
Please drop `}` to next line, and add trailing comma.  Prettier [subjective] and will reduce future diffs.

2017-02-11 20:16 UTC, cben commented on library/manageiq_provider.py
> +                               choices=['openshift-origin', 'openshift-enterprise', 'amazon', 'hawkular-datawarehouse']),
`choices=PROVIDER_TYPES.keys()`

2017-02-11 20:16 UTC, cben commented on library/manageiq_provider.py
> +            endpoints = [manageiq.generate_openshift_endpoint('default', 'default', hostname, port, token)]
They actually generate {'endpoint':..., 'authentication': ...} pairs, so "endpoint" is not best term.
The right term is "connection configuration", TLDR...  How about shorter:
`generate_auth_key_config`
`generate_user_password_config`

However, I'd maybe leave the amazon one called `generate_amazon_config`.  It's endpoint part is rather degenerate, just role without host/port or anything like that, not sure it'll suit providers.
Perhaps it's cleanest o split endpoint from auth, but let's wait until we add more providers.

2017-02-12 09:56 UTC, zgalor commented
> Should this use hawkular_hostname, hawkular_port params instead of hostname, port? Probably not.

@cben we shouldn't. A dw provider will later apply to ElasticSearch. We should use the generic hostname and port.

2017-02-12 13:12 UTC, zgalor commented
@dkorn @cben I made the changes you requested and added tests. Please review.

2017-02-12 14:45 UTC, cben commented
LGTM

2017-02-13 12:33 UTC, dkorn requested changes

2017-02-13 12:33 UTC, dkorn commented on README.md
>  The `manageiq_provider` module currently supports adding, updating and deleting OpenShift and Amazon EC2 providers to manageiq.
`supports adding, updating and deleting OpenShift, Amazon EC2 and **Hawkular** providers to manageiq`

2017-02-13 12:33 UTC, dkorn commented on tests/test_manageiq_provider.py
> +                                        HAWK_DW_PROVIDER_PORT, HAWK_DW_PROVIDER_TOKEN)]
small nit, fix indent

2017-02-13 12:33 UTC, dkorn commented on tests/test_manageiq_provider.py
>                                       password=AMAZON_PASSWORD)]
small nit, fix indent

2017-02-13 12:33 UTC, dkorn commented on tests/test_manageiq_provider.py
>                                          HAWKULAR_PORT, PROVIDER_TOKEN)]
small nit, fix indent

2017-02-13 12:33 UTC, dkorn commented on tests/test_manageiq_provider.py
>                                                 PROVIDER_HOSTNAME,
small nit, fix indent

2017-02-13 12:33 UTC, dkorn commented on library/manageiq_provider.py
> +            endpoints = [manageiq.generate_auth_key_config('default', 'default', hostname, port, token)]
I think we should include `"hawkular-datawarehouse"` in the first providers `if` block `("openshift-enterprise", "openshift-origin")` and add `PROVIDER_AUTH_TYPES` dict in `ManageIQ` class, to include these constants `('default'` for hawkular, `'bearer'` for the openshift providers). 
Perhaps also do that for the roles.

Not a blocker for this change, can also be part of a future refactor

2017-02-13 15:15 UTC, cben commented on library/manageiq_provider.py
> +            endpoints = [manageiq.generate_auth_key_config('default', 'default', hostname, port, token)]
I'd wait till we actually add more providers, we'll be smarter then.
Won't object if you/Zohar decide to refactor now.

2017-02-13 16:29 UTC, zgalor commented
@dkorn I fixed indentations and README.
Agree with @cben. We'll be smarter with the refactoring once we have more providers.

2017-02-14 08:59 UTC, dkorn approved these changes

2017-02-14 08:59 UTC, merged